### PR TITLE
fix: uri-encode slash in package name to support scopes

### LINKED ISSUE #24: Support scoped packages
Packages with scoped names (e.g. `@scope/pkg`) need to have the slash URL-encoded (e.g. `@scope%2Fpkg`), for any package name given to `ls()` or any dependencies encountered. Otherwise, the Couch registry returns 404.

This currently blocks the ability to manually add a scoped package to the whitelist in npm Enterprise (called via `package-whitelist`).

```
npme add-package @kadira/storybook
analyzing dependencies for @kadira/storybook:
Cannot convert undefined or null to object
[]
[?] add dependencies to /etc/npme/data/whitelist? (Y/n)
```

```
could not load @kadira/storybook@* status = 404
```

### PR DESCRIPTION
**Pull request by nexdrew**
Fixes #24.

Note that if/when https://github.com/npm/npm-package-arg/pull/18 lands and is published, we should replace this line:

```js
var couchPackageName = name && name.replace('/', '%2f')
```

with something like this:

```js
var couchPackageName = name && require('npm-package-arg')(name).escapedName
```

so that escaping logic can be centralized/reused.

### CODE REVIEW

**Comment by bcoe** [comment]
@nexdrew I tend to use the module [once](https://www.npmjs.com/package/once) if there is ever a need for this _only run once_ pattern.

**Comment by nexdrew** [comment]
@bcoe Great point, I updated it to use `once` instead.

**Comment by bcoe** [comment]
:shipit:

**Comment by nexdrew** [comment]
@bcoe I almost forgot about the CLI (which has no tests). That's fixed with commit d04a369.

**Pull request merged**
